name: apple_shop
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0

    
  loading_indicator: ^3.1.1
  dotted_line: ^3.2.2
  just_the_tooltip: ^0.0.12
  intl: ^0.19.0
  lottie: ^1.2.1
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0




  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  dio: ^5.4.0


  zarinpal: ^1.0.5
  uni_links: ^0.5.1
  url_launcher: ^6.2.4

  


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^2.0.0
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:


  uses-material-design: true


  assets:
   - images/
   - assets/


  fonts:
    - family: dana
      fonts:
        - asset: fonts/dana.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: fonts/GilroyBold.ttf
          weight: 500

    - family: GEB
      fonts:
        - asset: fonts/GilroyExtraBold.ttf
          weight: 700

    - family: GH
      fonts:
        - asset: fonts/GilroyHeavy.ttf
          weight: 900


    - family: GL
      fonts:
        - asset: fonts/GilroyLight.ttf
          weight: 100

    - family: GM
      fonts:
        - asset: fonts/GilroyMedium.ttf
          weight: 500

    - family: GR
      fonts:
        - asset: fonts/GilroyRegular.ttf
          weight: 400

    - family: GT
      fonts:
        - asset: fonts/GilroyThin.ttf
          weight: 300

    - family: SB
      fonts:
        - asset: fonts/ShabnamBold.ttf
          weight: 700

    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf
          weight: 500

